# Generated by Django 5.0.2 on 2024-03-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='text',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='travelchecklist',
            old_name='items',
            new_name='check_list',
        ),
    ]
