# Generated by Django 5.0.2 on 2024-03-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_rename_text_checklistitem_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='items',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='travelchecklist',
            old_name='check_list',
            new_name='items',
        ),
    ]
