# Generated by Django 5.0.2 on 2024-03-24 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_travelchecklist_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='travel',
            name='estimated_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
