# Generated by Django 5.0.2 on 2024-03-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='cel',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='compania',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='fecha_de_alta',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='notes',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='telefono',
        ),
    ]
