# Generated by Django 5.0.2 on 2024-03-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_last_name_contact_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='compania',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fecha_de_alta',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cel',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='notas',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='telefono',
            new_name='phone',
        ),
    ]
