# Generated by Django 5.0.2 on 2024-03-08 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='estimated_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
